### ISSUE TITLE
UI für Meme Ansicht erstellen

### ISSUE THREAD

**Issue by s-gbz** [s-gbz/meme-scout-25#12]
Unteraufgabe von #3 & #4

**Comment by BinaryPolar** [comment]
MemeView für Webbrowser 
![MemeView](https://user-images.githubusercontent.com/62502915/80221550-bd98e200-8645-11ea-9d9c-a21066f4119e.jpg)

**Comment by s-gbz** [comment]
Closed by recent PR.
